services:
  db:
    image: postgres:alpine
    container_name: exam_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0208"
      POSTGRES_DB: exam_bot
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql


  bot:
    build:
      context: .
      dockerfile: docker_file_bot/Dockerfile
    image: exam_bot:alpine
    container_name: exam_bot_con
    restart: always



  web:
    build:
      context: .
      dockerfile: docker_file_web/Dockerfile
    image: exam_web:alpine
    container_name: exam_web_con
    restart: always
    ports:
      - "8000:8000"


volumes:
  pg_data: